--liquibase formatted sql

--changeset 60098727:create:view:v_gold_order_corrections_analysis

CREATE OR REPLACE VIEW v_gold_order_corrections_analysis AS
select
     prop_id,
     orders,
     prop_date,
     order_date,
     delivery_date,
     cover_end_date,
     item,
     store,
     prop_qty,
     ord_qty,
     all_rounds_qty,
     stock_qty,
     intransit_qty,
     stock_days,
     qty_sold,
     reservs,
     l1,
     prop_targetstock,
     ord_targetstock,
     l2,
     pcb,
     need_qty,
     frsct_cov,
     pcb_round_qty,
     cov_period,
     srok,
     abc,
     l1_case,
     target_stock,
     money_user,
     money_gold,
     money_rounds,
     ostatoK2,
     E_rounds,
     ostatoK1,
     Е_user,
     E_gold,
     ostatoki_desc,
     updated_dttm
FROM gold_order_corrections_analysis
