--liquibase formatted sql

--changeset 60098727:create:view:v_tmp_corr_detailed

CREATE OR REPLACE VIEW v_tmp_corr_detailed AS
select site,
        code_internal,
        order_date,
        prop_number,
        prop_type,
        supp_int_code,
        prop_is_valid,
        prop_item_qty,
        prop_coeff_euro,
        prop_line_code,
        contract_numbers,
        ord_price,
        order_item_qty,
        ord_item_price,
        item_price,
        item,
        tech_case_no,
        prop_date,
        prp_amt,
        item_internal,
        cov_period,
        stock_qty,
        intransit_qty,
        lpcarrcde,
        lpccumbes,
        lpccumprev,
        sdpp,
        lpcarrref,
        pdcvapar,
        cover_delivery,
        delivery_date,
        cover_end_date,
        rms_reject,
        reject_reason
from tmp_corr_detailed
