--liquibase formatted sql

--changeset 60098727:create:table:trackandtrace_marts.kalypso_containers

CREATE TABLE kalypso_containers (
    oc_id text ENCODING (compresslevel=1,compresstype=zstd,blocksize=32768)
    , order_id text ENCODING (compresslevel=1,compresstype=zstd,blocksize=32768)
    , rms_order_id text ENCODING (compresslevel=1,compresstype=zstd,blocksize=32768)
    , adeo_order_id text ENCODING (compresslevel=1,compresstype=zstd,blocksize=32768)
    , invoice_id text ENCODING (compresslevel=1,compresstype=zstd,blocksize=32768)
    , container_id1 text ENCODING (compresslevel=1,compresstype=zstd,blocksize=32768)
    , container_id2 text ENCODING (compresslevel=1,compresstype=zstd,blocksize=32768)
    , container_creating_date date ENCODING (compresslevel=1,compresstype=zstd,blocksize=32768)
    , adeo_code text ENCODING (compresslevel=1,compresstype=zstd,blocksize=32768)
    , adeo_dep_name text  ENCODING (compresslevel=1,compresstype=zstd,blocksize=32768)
	, delivery_unit_ordered_unit_code text ENCODING (compresslevel=1,compresstype=zstd,blocksize=32768)
    , delivery_type text ENCODING (compresslevel=1,compresstype=zstd,blocksize=32768)
    , production_diff int ENCODING (compresslevel=1,compresstype=zstd,blocksize=32768)
    , purchasing_incoterm_code text ENCODING (compresslevel=1,compresstype=zstd,blocksize=32768)
    , purchasing_incoterm_city_code text ENCODING (compresslevel=1,compresstype=zstd,blocksize=32768)
    , country_of_loading_code text  ENCODING (compresslevel=1,compresstype=zstd,blocksize=32768)
	, country_of_loading_name text ENCODING (compresslevel=1,compresstype=zstd,blocksize=32768)
    , city_of_discharge_code text ENCODING (compresslevel=1,compresstype=zstd,blocksize=32768)
    , city_of_discharge_name text ENCODING (compresslevel=1,compresstype=zstd,blocksize=32768)
    , status_kalypso text ENCODING (compresslevel=1,compresstype=zstd,blocksize=32768)
    , shipped_container_number text ENCODING (compresslevel=1,compresstype=zstd,blocksize=32768)
    , delivered_container_number text  ENCODING (compresslevel=1,compresstype=zstd,blocksize=32768)
	, shipped_information_number_of_units numeric ENCODING (compresslevel=1,compresstype=zstd,blocksize=32768)
    , to_be_shipped_information_number_of_units numeric ENCODING (compresslevel=1,compresstype=zstd,blocksize=32768)
    , to_be_shipped_information_volume numeric ENCODING (compresslevel=1,compresstype=zstd,blocksize=32768)
    , shipped_information_volume numeric  ENCODING (compresslevel=1,compresstype=zstd,blocksize=32768)
	, updated_delivery_date date ENCODING (compresslevel=1,compresstype=zstd,blocksize=32768)
    , updated_shipping_date date ENCODING (compresslevel=1,compresstype=zstd,blocksize=32768)
    , shipment_comments text ENCODING (compresslevel=1,compresstype=zstd,blocksize=32768)
    , confirmed_delivery_date date ENCODING (compresslevel=1,compresstype=zstd,blocksize=32768)
    , confirmed_shipping_date date ENCODING (compresslevel=1,compresstype=zstd,blocksize=32768)
    , shipment_release_date date ENCODING (compresslevel=1,compresstype=zstd,blocksize=32768)
    , selling_invoice_date date ENCODING (compresslevel=1,compresstype=zstd,blocksize=32768)
	, container_type_1st_leg text ENCODING (compresslevel=1,compresstype=zstd,blocksize=32768)
    , loading_type_1st_leg text ENCODING (compresslevel=1,compresstype=zstd,blocksize=32768)
    , container_type_2nd_leg text ENCODING (compresslevel=1,compresstype=zstd,blocksize=32768)
    , loading_type_2nd_leg text ENCODING (compresslevel=1,compresstype=zstd,blocksize=32768)
    , forwarder_id text ENCODING (compresslevel=1,compresstype=zstd,blocksize=32768)
    , main_transport_company_id text ENCODING (compresslevel=1,compresstype=zstd,blocksize=32768)
    , bu_name text  ENCODING (compresslevel=1,compresstype=zstd,blocksize=32768)
    , dbf_kalypso_containers boolean ENCODING (compresslevel=1,compresstype=zstd,blocksize=32768)
)

WITH (appendonly='true', compresslevel='1', orientation='column', compresstype=zstd)
distributed by (order_id)
PARTITION BY RANGE (container_creating_date) (DEFAULT PARTITION other);
