--liquibase formatted sql

--changeset 60115905:create:table:trackandtrace_marts.ries_shipment_tracking


CREATE TABLE ries_shipment_tracking (
    oc_id text ENCODING (compresslevel=1,compresstype=zstd,blocksize=32768)
    , invoice_id text ENCODING (compresslevel=1,compresstype=zstd,blocksize=32768)
    , actual_container text ENCODING (compresslevel=1,compresstype=zstd,blocksize=32768)
    , container_id text ENCODING (compresslevel=1,compresstype=zstd,blocksize=32768)
    , swb text ENCODING (compresslevel=1,compresstype=zstd,blocksize=32768)
    , modified_container text ENCODING (compresslevel=1,compresstype=zstd,blocksize=32768)
  	, loading_type text ENCODING (compresslevel=1,compresstype=zstd,blocksize=32768)
    , container_type text ENCODING (compresslevel=1,compresstype=zstd,blocksize=32768)
    , custom_in_plan date ENCODING (compresslevel=1,compresstype=zstd,blocksize=32768)
    , destination_rail_station text ENCODING (compresslevel=1,compresstype=zstd,blocksize=32768)
    , truck_arr_pol_fact date ENCODING (compresslevel=1,compresstype=zstd,blocksize=32768)
    , rdd_pol date ENCODING (compresslevel=1,compresstype=zstd,blocksize=32768)
    , etd_pod_plan_fwr date  ENCODING (compresslevel=1,compresstype=zstd,blocksize=32768)
  	, rta_pod date ENCODING (compresslevel=1,compresstype=zstd,blocksize=32768)
    , etd_pod_plan date ENCODING (compresslevel=1,compresstype=zstd,blocksize=32768)
    , rdd_pod date ENCODING (compresslevel=1,compresstype=zstd,blocksize=32768)
    , rdd_rail_station date ENCODING (compresslevel=1,compresstype=zstd,blocksize=32768)
    , drop_off date ENCODING (compresslevel=1,compresstype=zstd,blocksize=32768)
    , rta_rail_station date ENCODING (compresslevel=1,compresstype=zstd,blocksize=32768)
    , arrival_wh_plan date ENCODING (compresslevel=1,compresstype=zstd,blocksize=32768)
    , arrival_wh_fact timestamp ENCODING (compresslevel=1,compresstype=zstd,blocksize=32768)
  	, forwarder_comments text ENCODING (compresslevel=1,compresstype=zstd,blocksize=32768)
    , tu text ENCODING (compresslevel=1,compresstype=zstd,blocksize=32768)
    , release_to text ENCODING (compresslevel=1,compresstype=zstd,blocksize=32768)
    , release_to_modified text ENCODING (compresslevel=1,compresstype=zstd,blocksize=32768)
    , transport_from_pod text ENCODING (compresslevel=1,compresstype=zstd,blocksize=32768)
    , loading_percent text ENCODING (compresslevel=1,compresstype=zstd,blocksize=32768)
    , fwr_appl_create_date date ENCODING (compresslevel=1,compresstype=zstd,blocksize=32768)
  	, fwr_appl_confirm_date date ENCODING (compresslevel=1,compresstype=zstd,blocksize=32768)
    , customs_terminal text ENCODING (compresslevel=1,compresstype=zstd,blocksize=32768)
    , customs_broker text ENCODING (compresslevel=1,compresstype=zstd,blocksize=32768)
    , comments_broker text ENCODING (compresslevel=1,compresstype=zstd,blocksize=32768)
    , custom_in_fact date ENCODING (compresslevel=1,compresstype=zstd,blocksize=32768)
    , import_specialist text ENCODING (compresslevel=1,compresstype=zstd,blocksize=32768)
  	, cd_specialist text ENCODING (compresslevel=1,compresstype=zstd,blocksize=32768)
    , certification_specialist text ENCODING (compresslevel=1,compresstype=zstd,blocksize=32768)
    , port_of_discharge text ENCODING (compresslevel=1,compresstype=zstd,blocksize=32768)
    , etd_pol_plan date ENCODING (compresslevel=1,compresstype=zstd,blocksize=32768)
    , dbf_ries_shipment_tracking boolean ENCODING (compresslevel=1,compresstype=zstd,blocksize=32768)
)
WITH (appendonly='true', compresslevel='1', orientation='column', compresstype=zstd)
distributed by (oc_id);
