create or replace view v_ries_shipment_tracking as
 select oc_id
   , invoice_id
   , actual_container
   , container_id
   , swb
   , modified_container
   , loading_type
   , container_type
   , custom_in_plan
   , destination_rail_station
   , truck_arr_pol_fact
   , rdd_pol
   , etd_pod_plan_fwr
   , rta_pod
   , etd_pod_plan
   , rdd_pod
   , rdd_rail_station
   , drop_off
   , rta_rail_station
   , arrival_wh_plan
   , arrival_wh_fact
   , forwarder_comments
   , tu
   , release_to
   , release_to_modified
   , transport_from_pod
   , loading_percent
   , fwr_appl_create_date
   , fwr_appl_confirm_date
   , customs_terminal
   , customs_broker
   , comments_broker
   , custom_in_fact
   , import_specialist
   , cd_specialist
   , certification_specialist
   , port_of_discharge
   , etd_pol_plan
   , dbf_ries_shipment_tracking
 from ries_shipment_tracking;
