create or replace view v_ries_orders as
select order_id
    , order_date
    , order_status
    , oc_id
    , priority
    , oc_date
    , adeo_code
    , lm_code
    , ean_code
    , etd_oc
    , eta_oc
    , port_of_loading
    , incoterms
    , season_validity_date_from
    , season_validity_date_to
    , oc_total_amount
    , route_id
    , manufacturer
    , desc_eng
    , ries_order_qty
    , article_total_amount
    , under_certification
    , samples_qty
    , samples_required
    , doc_serial_id
    , doc_serial_valid
    , doc_type
    , doc_batch_issue
    , doc_serial_expiry
    , doc_batch_id
    , tech_regulation
    , awb_or_container_samples_id
    , samples_pi_id
    , initial_pi_sending_date
    , deadline_pi_sending_date
    , sample_sending_way
    , sample_sending_date
    , deadline_sample_sending_date
    , sample_sending_kpi
    , reason_sample_sending_late
    , sample_sending_delay
    , calculated_etd
    , comments_for_etd
    , transport_instruction
    , dbf_ries_orders
    , samples_sent_code
    , samples_required_code
from ries_orders;
